openshift/baremetal-runtimecfg

pkg/config/node.go

If the cluster-config.yml is passed to runtimecfg, it should use that
first, and fall back to kubeconfig to get the cluster name and
domain.
Fixes #15

Use cluster-config.yml first for cluster name and domain

---

pkg/monitor/monitor.go

If Haproxy went down for some reason, the Iptable rule that
redirects API traffic to Haproxy LB, should be removed.

Monitor - delete iptable rule if API not reachable through Haproxy

---

pkg/monitor/monitor.go

With the previous code we'd have an issue where if there would be an SRV
record for a node that was just taken down, we'd have a "blank" backend
in the configuration.
Fixes #17

Do not consider unresolvable backends

---

.gitignore
Dockerfile
cmd/dynkeepalived/dynkeepalived.go
pkg/config/node.go
pkg/monitor/dynkeepalived.go
pkg/monitor/monitor.go
test/data/config.hcl.tmpl

Using runtimecfg render for keepalived has the issue that on 1.x
keepalived versions there's no dynamic interfaces and in case the
interface changes, keepalived will stop doing its job.
Thanks to dynkeepalived, it is now possible to have it monitor the
interface and dynamically send a reload to a unix socket that can be
used to trigger a keepalived reload in the keepalived container.
This is meant to be used from a side-car to the keepalived pod.

Add dynkeepalived to solve interface changes

---

cmd/runtimecfg/runtimecfg.go
pkg/config/node.go
pkg/monitor/dynkeepalived.go

This will enable use cases where the upstreams you want in coredns
runtime are different than those that should be used by kubelet for the
pods.

Allow passing a path to resolvconf

---

Makefile

Previously the makefile only ran go fmt but didn't verify whether it
had to make changes. This adds a git diff --exit-code call to the
target so it will fail if the code was not formatted properly.

Check that go fmt has no changes

---

cmd/monitor/monitor.go
pkg/monitor/monitor.go
pkg/utils/utils.go

Monitor checks periodically for changes in masters topology, K8S API health via Haproxy
and updates load balancer configuration correspondingly.
To make the monitoring process more robust, this commit adds stabilization mechanism to
the periodic checks, means that Monitor will update load balancer configuration
only after it detects a change for N consecutive intervals.

Add stabilization mechanism to monitor logic

---

pkg/config/node.go
pkg/utils/utils.go

This change modifies how we calculate the fletcher8 checksum to
match the online calculators (for example, [0]). This has two
important effects:
1) The maximum value it can return is now 0xEE rather than 0xFF.
This is a documented limitation of the fletcher algorithm because
it uses modulo operations and 0xF % 0xF is 0, not 0xF, so it's
impossible to get a 0xF byte. Unfortunately, this does reduce the
id space available.
2) Because the algorithm will not return 255, we can safely add one
to the resulting value to ensure we don't end up with a VRID of
0. 0 is not a valid VRID for keepalived, as reported in #21.
0: https://gchq.github.io/CyberChef/#recipe=Fletcher-8_Checksum()&input=bDN2dnFxbmktZjIxY2EtZG5z

Tweak VRID calculation to avoid 0

---

pkg/config/node.go

This allows baremetal-runtimecfg to be used for generating the list
of etcd members for bootstrapping.

Add EtcdBackends cluster member

---

pkg/monitor/monitor.go

Due to multi-process implementation of the monitor code (it's a corner case),
we may hit a race condition and as a result of this race, the iptable rule won't be deleted.
This fix verifies that the iptable rule is deleted.

Verify that Iptable rule being deleted

---

pkg/config/net.go

In order to select an interface for the VIPs we
are trying to find a interface with an IP in the
same subnet.
If using DHCPv6 then addresses have a /128 address,
assume in this case its enough to test if the VIP
is in the same /64.

Convert /128 addresses to /64

---

pkg/config/net.go

This reverts commit 24845d3960ce1dcadac2dfaaac089783ba2aace7.
Passing an ipaddress through net.ParseCIDR ends up stripping
out averything but the network part of the IPaddress.

Revert "Convert /128 addresses to /64"

---

pkg/config/net.go

In order to select an interface for the VIPs we
are trying to find a interface with an IP in the
same subnet.
If using DHCPv6 then addresses have a /128 address,
assume in this case its enough to test if the VIP
is in the same /64.
Return the original IP address unchanged, the previous
version of this patch returned the network address in
error.

Convert /128 addresses to /64 again

---

pkg/utils/utils.go

The utils.ShortHostname function should read hostname from mdns
hostname, if mdns hostname file exists.
This mdns hostname file creation is handled by [1] MCO PR.
[1] https://github.com/openshift/machine-config-operator/pull/1446crea

Bug 1790823: Consider mdns hostname file existence in utils.ShortHostname

---

scripts/nodeip-finder
scripts/non-virtual-ip

MCO is placing a script on every node to setup non-virtual-ip via NM (see https://github.com/openshift/machine-config-operator/blob/fcos/templates/worker/00-worker/openstack/files/openstack-non-virtual-ip.yaml)
This script runs on host and requires Python on host. Instead this script should be in `baremetalcfg-runtime` container. MCO should use a podman wrapper with `--net=host` to run it in container, as some hosts (e.g. Fedora CoreOS) may not have python installed.
Eventually this script should be rewritten in golang.
Reference: https://github.com/openshift/machine-config-operator/issues/1430

Add non-virtual-ip script

---

.gitignore
Dockerfile
cmd/corednsmonitor/corednsmonitor.go
pkg/monitor/corednsmonitor.go
pkg/utils/utils.go

The runtimecfg render for coredns runs as initcontainer and
is responsible for Corefile composing.
With coredns-monitor it's possible to watch for changes in
NetworkManager resolv.conf file and update Corefile correspondingly.

Add support for coredns Corefile watcher

---

.gitignore
Dockerfile
cmd/corednsmonitor/corednsmonitor.go
pkg/monitor/corednsmonitor.go
pkg/utils/utils.go

Since  Corefile rendering for the Coredns container runs as initcontainer, changes to /etc/resolv.conf that happened after Coredns rendering completed won't be applied to Coredns Corefile.
With coredns-monitor we should be able to watch those changes and update Corefile correspondingly.

Bug 1812526: [release-4.4]  Add support for coredns watcher

---

cmd/monitor/monitor.go
cmd/runtimecfg/display.go
cmd/runtimecfg/render.go

The "Recovering from expired control plane certificates" procedure [1]
stands up a recovery API server on port 7443 [2], conflicting with the
port the haproxy process is listening on.
This patch moves the haproxy port to 9443 instead.
[1] https://docs.openshift.com/container-platform/4.3/backup_and_restore/disaster_recovery/scenario-3-expired-certs.html
[2] https://github.com/openshift/cluster-kube-apiserver-operator/blob/3161546a248f20eb67231017d0ae43c245bfa4cb/pkg/recovery/apiserver.go#L307

Bug 1821720: Move haproxy listening port due to conflict

---

pkg/config/node.go

Coredns will fail to start if we configure the forward plugin with
no upstream servers. The init container responsible for rendering
the config needs to fail if that situation arises so it can be
retried later when hopefully resolv.conf has been populated correctly.
We're not sure how it happens that there are no upstream servers,
but it's clearly wrong for us to render an invalid config so this
is the safe thing to do anyway.

Bug 1840222: Fail if no upstream DNS servers are found

---

pkg/config/node.go

We add records for some of the VIPs to our internal coredns server.
These records need to be of the appropriate type for the ip version
used. This change adds record type fields to the cluster for use
in the coredns config file. Two fields are added for each VIP:
One that specifies the correct type of record, and one that specifies
the other so that we are able to correctly handle requests for the
wrong record type too.

Add A/AAAA record types for VIP DNS entries

---

cmd/monitor/monitor.go
cmd/runtimecfg/runtimecfg.go

The "Recovering from expired control plane certificates" procedure [1]
stands up a recovery API server on port 7443 [2], conflicting with the
port the haproxy process is listening on.
This patch moves the haproxy port to 9443 instead.
[1] https://docs.openshift.com/container-platform/4.3/backup_and_restore/disaster_recovery/scenario-3-expired-certs.html
[2] https://github.com/openshift/cluster-kube-apiserver-operator/blob/3161546a248f20eb67231017d0ae43c245bfa4cb/pkg/recovery/apiserver.go#L307
Manual cherry-pick of https://github.com/openshift/baremetal-runtimecfg/pull/59/

Bug 1831008: Move haproxy listening port due to conflict

---

pkg/utils/utils.go
test/data/keepalived.conf.tmpl

The utils.GetEtcdSRVMembers() is no longer used after
https://github.com/openshift/baremetal-runtimecfg/pull/52/
Also removes the `chk_dns` script from the test keepalived config to
remove all trace of etcd SRV records in baremetal-runtimecfg.

Remove unused utils.GetEtcdSRVMembers() function

---

pkg/utils/utils.go

K8s health check should use localhost instead of 127.0.0.1 to support both
IPv6 and IPv4

Bug 1847086 : Update kube-api health check to use localhost

---

cmd/monitor/monitor.go
cmd/runtimecfg/display.go
cmd/runtimecfg/render.go

HAProxy port was moved on [1] to 9443, this cinflicted with KCM recovery container
which is using 9443 since 4.3. on [2] KCM added a check that the port is free which
caused a conflict and a crashlooping pod.
[1] https://github.com/openshift/baremetal-runtimecfg/pull/59
[2] https://github.com/openshift/cluster-kube-controller-manager-operator/pull/421
Signed-off-by: Gal-Zaidman <gzaidman@redhat.com>

BUG 1853889: Move haproxy port to 9445 due to conflict with KCM

---

Dockerfile

In recent images there are iptables binaries in /usr/sbin/ in
addition to/in place of /usr/bin. This is causing problems because
/usr/sbin is in the PATH before /usr/bin so our code is calling the
wrong iptables. We can just copy the iptables scripts into /usr/sbin
and take care of the problem.

Bug 1857672: Also copy iptables scripts to /usr/sbin

---

.gitignore
Dockerfile
cmd/unicastipserver/unicastipserver.go
go.sum
pkg/config/node.go
pkg/monitor/dynkeepalived.go
pkg/monitor/unicastipserver.go

With this PR keepalived capability extended to support both unicast and multicast modes.
The following components were updated to support unicast mode:
- A simple server that will return node's non-virtual IP address, this server will be used
by the master nodes to retrieve the bootstrap node IP address. One should contact the server on port 64444.
- keepalived-monitor can render conf file to support unicast or multicast mode, based on configuration.

Add support for unicast keepalived

---

pkg/monitor/lease.go

In order to monitor `dhclient` behavior - Channels the command `stderr` stream

Stream dhclient stderr logs

---

pkg/monitor/lease.go
pkg/monitor/lease_test.go

No need to support BRIDGE mode.
Private mode doesn’t allow communication between MACVLAN instances on the same physical interface.

Change macvlan to be private mode

---

pkg/config/node.go
pkg/monitor/dynkeepalived.go

starting from 4.6 we plan to change keepalived to run in unicast mode for baremetal.
As a result of that change we need also to support the following requirements :
A. For upgrade to 4.6 case, we need to change Keepalived mode to unicast post-upgrade ( without user intervention).
B. In case of breakage, we want to allow the user to flip mode.
With this PR, the keepalived watcher sidecar will monitor a file with a predefined name, once the file has been
identified by the sidecar container the following actions will be carried out:
- Verification that desired mode is different from current mode (otherwise exit)
- Verification that upgrade process is completed, by the comparison between values of machineconfiguration.openshift.io/currentConfig and …

Add support for Keepalived mode update

---

pkg/monitor/dynkeepalived.go

Keepalived monitor reads every x seconds the current configuration, it compares it to the previous configuration. In case a change is detected a new Keepalived conf file is rendered. 
In one of the latest commits the variable used to store the current config changed by mistake to be local variable instead of runtime-created variable (e.g: newConfig  := some_value ).
This PR fixes this mistake.

Bug 1867080 : Keepalived monitor - store correctly current configuration

---

Dockerfile

dhcp-client is the new name for the dhclient package in RHEL 8.
Since our images are currently still being built with RHEL 7, this
is causing our image builds to fail. Using the old name should work
in both versions, so until the RHEL 8 transition happens let's use
it.
Note that even though the Dockerfile says to use ubi8, that is
ignored in the product image builds.

Install dhclient instead of dhcp-client

---

Dockerfile

This is required for the haproxy-monitor liveness probe. It apparently
got dropped when we switched to the ubi8 image.

Install diffutils in image

---

cmd/monitor/monitor.go
cmd/runtimecfg/runtimecfg.go

** cherry pick for [3][4] **
HAProxy port was moved on [1] to 9443, this cinflicted with KCM recovery container
which is using 9443 since 4.3. on [2] KCM added a check that the port is free which
caused a conflict and a crashlooping pod.
[1] https://github.com/openshift/baremetal-runtimecfg/pull/61
[2] openshift/cluster-kube-controller-manager-operator#423
[3]https://github.com/openshift/baremetal-runtimecfg/pull/71
[4]https://github.com/openshift/baremetal-runtimecfg/pull/73
Signed-off-by: Gal-Zaidman <gzaidman@redhat.com>

Bug 1862898: Move haproxy port to 9445 due to conflict with KCM

---

Dockerfile.openshift

We want to use this Dockerfile for CI so that local builds will continue
to use the ubi8 image.

Bug 1872080: Add Dockerfile.openshift for CI

---

pkg/config/node.go

To work around [1]  bug in network manager the subnet mask of Keepalived VIP address was set to the value of control plane IP subnet mask.
So, after the network manager bug was resolved we can safely change VIP subnet mask to a host subnet mask.
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1700415

Change keepalived VIP subnet mask to host mask

---

pkg/config/node.go
pkg/monitor/dynkeepalived.go

When OPENSHIFT_INSTALL_PRESERVE_BOOTSTRAP deployment configuration parameter is set to true the
bootstrap node won't be destroyed and the infrastructure components including Keepalived on the bootstrap continue to run.
With this PR a stop message is sent to Keepalived control socket when the API server is not operational anymore on bootstrap node.
This change is important for platforms that run Keepalived in unicast mode (baremetal).

Bug 1866265: Stop Keepalived on bootstrap after bootstrap completed

---

cmd/runtimecfg/node-ip.go
pkg/utils/utils.go

"runtimecfg node-ip" is currently only used on bare metal IPI, and depends on being given an apiserver VIP to use as a hint to figure out the node IP to use. In some cases kubelet also needs help figuring out the default node IP on bare metal UPI, but we have no apiserver VIP to use there. This extends "runtimecfg node-ip" to allow running with no VIPs, in which case it just picks an IP based on the default route.
/cc @celebdor

Bug 1872632: runtimecfg node-ip: allow running without VIPs

---

pkg/monitor/dynkeepalived.go

In order to keep the VIP in the bootstrap node until the masters' API shows up, we increased the priority of the bootstrap keepalived API VIP membership. In order for the VIP to successfully move to the masters even when the bootstrap is requested to stay even after clustering (when its API server is already gone), we implemented a mechanism in the monitor that stops it. The problem with that was that sometimes, during a clustering, the API in the bootstrap node could go down for long enough that it looked like it would not go up anymore.
This PR addresses it by continuing to check for the API server on the bootstrap node, and reloading keepalived if it shows up again. In case it is gone for good, the behavior will be the same, but if it just went down for a while because of API pod …

Bug 1884420: bootstrap: API shows up, start it again

---

Dockerfile

Now that CI and Productization uses Dockerfile.openshift, the "main"
Dockerfile is free to use CentOS 8. This should limit the drift.

Change local Dockerfile to use CentOS 8

---

Dockerfile.openshift

Updating baremetal-runtimecfg builder & base images to be consistent with ART
Reconciling with https://github.com/openshift/ocp-build-data/tree/f66c03011773dc3755ad874fc691be612914d65f/images/baremetal-runtimecfg.yml
If you have any questions about this pull request, please reach out to `@art-team` in the `#aos-art` coreos slack channel.
Depends on https://github.com/openshift/images/pull/44 . Allow it to merge and then run `/test all` on this PR.

Updating baremetal-runtimecfg builder & base images to be consistent with ART

---

pkg/config/node.go

In 4.5 to 4.6 upgrade we support automatic Keepalived mode flip to unicast,
the change to unicast should start only after MCO finished configuring the 4.6 desired state
in all the nodes.
With this PR the flip mode starts only after all the nodes configured with the new MCO configuration.

Bug 1885867 :  Flip to unicast only when MCO set to desired version in all nodes

---

Makefile

Add image build and push to the Makefile

---

cmd/dynkeepalived/dynkeepalived.go
cmd/monitor/monitor.go
pkg/config/node.go
pkg/monitor/dynkeepalived.go
pkg/monitor/iptables.go
pkg/monitor/monitor.go
pkg/render/render.go

Manual backport of #70 to release-4.5.
I squashed all the commits from #70 into one and added a new commit on top of it to deal with the difference between the branches and how the new behavior affects keepalived when the executable bit is set on its config file.
This PR was missed when backporting https://github.com/openshift/machine-config-operator/pull/2110 for OpenStack platform.

Bug 1888301: Add check for iptables rule to keepalived-monitor

---

cmd/runtimecfg/node-ip.go
pkg/config/net.go
pkg/config/node.go

There are a few problems preventing `baremetal-runtimecfg` to work when the node isn't attached to the VIP network.
- The `render` command complains when the node is not on a subnet on which the VIP is routable.
- The `node-ip` accepts running without providing a VIP, but still complains when we pass it a VIP and the node isn't attached to the subnet including the VIP.
This is a first step to support deploying additional machinesets on separate subnets.

Bug 1894539: Allow baremetal-runtimecfg to function when the node isn't attached to the VIP network

---

pkg/monitor/lease.go

Matching https://github.com/openshift/assisted-installer-agent/pull/92
Solves [MGMT-2219 DHCP hostname unique prefix](https://issues.redhat.com/browse/MGMT-2219)

Set mac address as prefix for unique hostname

---

cmd/runtimecfg/node-ip.go
pkg/utils/addresses.go
pkg/utils/addresses_test.go
pkg/utils/utils.go

In kube 1.20 you can pass two IPs to `kubelet --node-ip`, but we still need help from runtimecfg to find the _right_ IPs.
First commit is just a reorg, second commit adds unit tests without changing functionality, and then the third commit changes the utils functions to return dual-stack answers and changes runtimecfg to make use of it. (Previously the utils functions returned multiple IPs of the same family but the caller only ever used the first value, so this just changes it to return only that first value, plus a second value of the opposite family.)
(I still need to write the corresponding MCO change and test it all...)

Update "runtimecfg node-ip" for dual-stack

---

cmd/runtimecfg/node-ip.go

Fall back to IP addresses associated with the default route in the when
the node is not on a subnet containing any of the VIPs.
Restore the feature implemented in
384c50336098baf83cb66c823cf142408d5ba8cf and broken with 83d05afd1b76b8f0078887f1001e722284235a3a.

Bug 1894539: Allow node-ip to function without attachment to VIP network

---

cmd/runtimecfg/node-ip.go
pkg/config/net.go
pkg/utils/addresses.go
pkg/utils/addresses_test.go
pkg/utils/utils.go

Since DHCPv6 assigns addresses with a /128, only the first 64 bits are considered when the VIP address is compared with the interface address, see [1].  
Comparing only the first 64 bits of the candidate address with the VIP address might lead for choosing the wrong interface in case of overlapping subnets , see [2] as an example .
To handle the overlapping IPV6 subnets case, we should also verify that the candidate address and VIP are L2 connected.
[1] https://github.com/openshift/baremetal-runtimecfg/blob/master/pkg/config/net.go#L39-#L41
[2]
2 interfaces:
Interface A subnet: 1001:db8::/120 , Interface B subnet: 1001:db8::f00/120
VIP address 1001:db8::64

Bug 1905233:  get the correct VRRP interface in case of IPV6 overlapping subnets

---

pkg/utils/utils.go

We noticed a linearly growing number of TCP connections in HAProxy in all clusters,
that are caused by periodic K8S API health check calls by the haproxy-monitor.
This PR verifies that unneeded HTTP connections used for checking API health being closed.

Bug 1915080: add CloseIdleConnections for HTTP K8S API healthcheck

---

Dockerfile
cmd/dnsmasqmonitor/dnsmasqmonitor.go
pkg/monitor/dnsmasqmonitor.go

This is for a simple monitor container that will simply watch the
cluster-hosted-net-services-operator configmap and update the api-int
record in dnsmasq appropriately. If it detects that the content of
the file has changed, it will overwrite the existing api-int.host
file and send the ClearCache dbus command to dnsmasq to reload its
configuration.

Add dnsmasqmonitor

---

Dockerfile

The old registry doesn't play nicely with dev-scripts.

Switch Dockerfile to new image registry

---

Dockerfile
Dockerfile.openshift

This reduces image build time by about half (1:38 vs 3:13 in my local
env) because we don't have to create so many layers.

Build all commands at once in Dockerfiles

---

cmd/runtimecfg/node-ip.go
pkg/config/net.go
pkg/utils/addresses.go
pkg/utils/addresses_test.go

Two tweaks to `node-ip` behavior in the UPI case:
- If there are two interfaces with equal-priority default routes, use the IPs from the one with the lower ifindex. AFAIK this isn't actually affecting anyone yet, but if someone _did_ do this, then with the current code we'd randomly flip between the interfaces/addresses based on the order golang happened to iterate the map in. This makes us not do that.
- This adds `--prefer-ipv6` so you can clarify whether you want an IPv4 or IPv6 address for single-stack kubernetes on dual-stack nodes (which is what the linked bz is)

Bug 1939740: sort AddressesDefault by ifindex and IPv4/IPv6 preference

---

cmd/runtimecfg/node-ip.go
pkg/config/net.go
pkg/utils/addresses.go
pkg/utils/addresses_test.go

backport of #130 because I need it, plus #125 for ease of backporting and since we should probably have it in 4.7 anyway.
(cherry-pick-bot couldn't backport #130 itself because of the #125 dependency)
/cc @cybertron @celebdor

Bug 1942488: sort AddressesDefault by route priority, ifindex, and IPv4/IPv6 preference

---

pkg/monitor/dynkeepalived.go

Empty unicast peers list on Keepalived config on one of the master nodes is an invalid use case (that may cause to two nodes hold the VIP).
Monitor container code should verify that generated keepalive config file doesn't include empty unicast peers list, this is [the current code](https://github.com/openshift/baremetal-runtimecfg/blob/master/pkg/monitor/dynkeepalived.go#L84) that verify this case.
But in case only a single master node (for example master-1) was registered to cluster we'll end up with empty unicast peers list in master-1 keepalived conf ( check - https://github.com/openshift/machine-config-operator/blob/master/templates/master/00-master/on-prem/files/keepalived-keepalived.yaml#L54-#L60 ) .
This fix should verify that unicast peers list isn't empty

Bug 1957708:  Keepalived- verify that unicast peers list isn't empty on master nodes

---

pkg/render/render.go

When debugging problems related to services whose config files are
rendered by baremetal-runtimecfg, it can be helpful to see exactly
what was rendered. This change adds log output of the full config
as generated by the templating process.

Bug 1960716: Log the output of render operations

---

cmd/runtimecfg/node-ip.go
pkg/config/net.go
pkg/utils/addresses.go
pkg/utils/addresses_test.go
pkg/utils/utils.go

This started because I need to backport #130 to 4.6, but it didn't backport cleanly at all because there have been a bunch of node-ip changes since then...
Given that 4.6 is our extended support release, it is probably good to get all the bug-fix-y bits backported. We don't actually need the dual-stack support in 4.6 (and I don't plan to backport the corresponding MCO part of that) but including it makes it easier to backport the rest of it... (We do expect to have at least one customer running single-stack IPv6 for a while in 4.6, hence the need for the #130 backport.)
/cc @cybertron @celebdor

Bug 1942506: 4.6 EUS node-ip handling extravaganza

---

pkg/config/node.go
pkg/monitor/dynkeepalived.go

Ingress VIP should be set only on a node that runs an instance of the default ingress controller pod.
In current code, in case extra ingress-controllers are created the ingress VIP might be wrongly set on a node that doesn't run
an instance of the default ingress controller.
This PR calculates the priority for keepalived ingress VIP depending on the presence of the router pod in the node by monitoring the content of router-internal-default endpoints resource.

Bug 1886572: Calculate keepalived priority for ingress

---

pkg/config/node.go
pkg/monitor/dynkeepalived.go

This reverts commit c8b1456c0f0aa124490b47281557a1beaa5afcf1, reversing
changes made to e6b36b2bd8ce7af2743005376e7bff48dcd4010f.
We can merge this PR after https://github.com/openshift/machine-config-operator/pull/2637 will be merged

Revert "Merge pull request #141 from yboaron/get_endpoints"

---

pkg/config/node.go
pkg/monitor/dynkeepalived.go

In case of dual-stack deployment, configure unicast_peer of ingress
VRRP instance with single type (v4/v6) IPs

Bug 1998951: retrieve only single type  addresses for Keepalived ingress

---

cmd/monitor/monitor.go
cmd/runtimecfg/display.go
cmd/runtimecfg/render.go

The haproxy stats and health endpoints were configured with high
port numbers (50000 and 50936) that conflict with the range used for
dynamic allocation of ports:
$ cat /proc/sys/net/ipv4/ip_local_port_range
32768   60999
This can occasionally cause haproxy to fail if the kernel happens to
pick one of those ports for a client connection.
To avoid this, we should use ports outside the range shown above.
This patch changes the stats endpoint to 30000, while the health
endpoint is controlled by the MCO config and will be fixed in a
separate commit there.

Bug 2012780: Avoid dynamically allocated port range for haproxy

---

pkg/monitor/dynkeepalived.go

In some environments we seem to be hitting an edge case where more
than one message backs up on the bootstrapStopKeepalived queue,
which means it is possible for a stop and reload message to be sent
back to back. It appears that the stop function on the keepalived
side takes longer, and as a result reload completes before stop
and it sends a SIGHUP to a process that's about to be killed instead
of restarting keepalived like we want.
This patch adds a 5 second delay after a stop or reload message is
sent so keepalived should have plenty of time to process it before
another message comes in.

Bug 2022050: Add delay after sending bootstrap stop and start messages

---

pkg/utils/addresses.go

Currently the logic in node-ip show allows a VIP to be selected as
the node IP. This is incorrect, although it doesn't generally cause
a problem today because it appears the VIP is ordered after the
correct node IP in the list. However, we shouldn't rely on that
ordering to ensure we pick the correct address.
Note that this was discovered due to a misconfiguration in a cluster
where the VIP was placed on a node that had an address in a different
subnet. In this case, the node IP didn't match so the VIP was
subsequently checked and found to match (because of course it does).
This caused the VIP to be selected as the node IP, which is also an
error. While this scenario is invalid, it does show that it is
possible for the VIP to be selected as a node IP and we should not
allow that.
This …

Bug 2021544: Ignore VIPs in node-ip show

---

Dockerfile.unittest
docker-compose.yaml

The `docker_test` target was failing because of some outdated image references. This PR fixes it so `make docker_test` can run again

Fix docker_test run

---

cmd/dynkeepalived/dynkeepalived.go

When an error of any type happens in dynkeepalived, the usage help message is output. This implies that there was a problem with the options passed to the CLI, but in most cases that is not the case. This unnecessary output also tends to hide the actual error message.
This PR addresses it and silences usage when an error occurs:
```
$ go run ./cmd/dynkeepalived/dynkeepalived.go test/data/kubeconfig /tmp /tmp
INFO[0000] Monitor conf file doesn't exist               file=/unsupported-monitor.conf
Error: dial unix /var/run/keepalived/keepalived.sock: connect: no such file or directory
FATA[0000] Failed due to dial unix /var/run/keepalived/keepalived.sock: connect: no such file or directory 
exit status 1
```
Missing parameter still shows the usage:
```
$ go run …
```

Bug 2000236: Disable printing usage help on error

---

Dockerfile

Avoid errors related to appstream repo.
Signed-off-by: Douglas Schilling Landgraf <dougsland@redhat.com>

Dockerfile: migrate repo to CentOS 8 Stream

---

cmd/monitor/monitor.go
cmd/runtimecfg/display.go
cmd/runtimecfg/render.go

Per [0], the range 30000-32767 is used for kubernetes node ports.
We should not have haproxy listening in that range to avoid possible
conflicts.
0: https://github.com/openshift/openshift-docs/blob/main/modules/installation-network-user-infra.adoc

Bug 2069740: Avoid kubernetes node port range

---

cmd/runtimecfg/node-ip.go

In IPv6, if the chosen IP address is still tentative
then it can't be bound to, resulting in crio crashing.
Check that the IP address can be used and if not fail
or retry as appropriate.

Bug 2096226: Check chosen node-ip can be used

---

cmd/corednsmonitor/corednsmonitor.go
cmd/dnsmasqmonitor/dnsmasqmonitor.go
cmd/dynkeepalived/dynkeepalived.go
cmd/monitor/monitor.go
cmd/runtimecfg/display.go
cmd/runtimecfg/render.go
pkg/config/net.go
pkg/config/node.go
pkg/monitor/corednsmonitor.go
pkg/monitor/dnsmasqmonitor.go
pkg/monitor/dynkeepalived.go
pkg/monitor/lease.go
pkg/monitor/lease_test.go
pkg/monitor/monitor.go
pkg/utils/addresses.go

There are fields throughout the Node object that depend on the IP
version of the VIPs. In order to handle the new addition of
multiple VIPs for dual stack clusters we are going to need two
copies of these objects populated with the appropriate values.
This change keeps the first Node object as the top-level config
object for backward compatibility, but adds a new pointer to a list
of Node objects that will allow us to iterate it in templates and
implement both IP versions.

Add list of Node configs to handle multiple VIPs

---

cmd/runtimecfg/node-ip.go

Because chosen is function-scoped, it is persistent over multiple
iterations of the loop. If the first iteration fails and we retry,
the second time around we skip the AddressesDefault case because
chosen is no longer empty. This means the retries will never succeed.
If we just re-initialize the chosen list before retrying then it
should get repopulated the next time through and the retry mechanism
will work as expected.

OCPBUGS-669: Empty chosen list when retrying ip selection

---

pkg/config/node.go

#196 fails due to format issues in node.go. This PR addresses it and formats the go files.

Run go fmt

---

cmd/runtimecfg/node-ip.go

Backport of the two patches needed to make the ipv6 bind check work on UPI platforms too.

OCPBUGS-673: Apply ipv6 bind check to non-VIP case too

---

pkg/config/node.go
pkg/utils/utils.go

OCPBUGS-2994: Keepalived monitor stuck for long period of time on kube-api call while installing
While installing kube-api server is not stable and keepalived-monitor can stuck while trying to get nodes

OCPBUGS-2994: Adding timeout for kubeapi calls for keepalived monitor

---

OWNERS

We are perpetually short on approvers for this repo because the team keeps changing. Martin and Igal have done quite a bit of work in and related to this repo so I would be comfortable with them approving changes, especially if we're in a situation where our on-prem networking approver(s) are not available.
I'm not adding them to the reviewers list because I doubt they want to be auto-assigned to patches here, but I'm happy to change that if I'm wrong. :-)

Add mandre and tsorya as approvers

---

cmd/runtimecfg/node-ip.go
pkg/utils/addresses.go
pkg/utils/addresses_test.go

Adding network type in order to be able to filter ovn ipv6 ip

OCPBUGS-6004: filter ovn fd69::2 ip from list of ips in case ovn

---

cmd/runtimecfg/node-ip.go

We want it to be a persistent flag available for all subcommands.

node-ip: fix user-managed-lb flag

---

cmd/runtimecfg/node-ip.go
pkg/config/net.go
pkg/utils/addresses.go
pkg/utils/addresses_test.go

We added support for the preferIPv6 option in node-ip selection for UPI, but since we always preferred IPv4 in IPI except in v6-only deployments it wasn't wired in for the IPI path. This patch fixes that so we can do v6-primary dual stack deployments and select the appropriate node ip.

OPNET-210: Support preferIPv6 for IPI too

---

pkg/config/node.go
pkg/config/node_test.go
pkg/monitor/dynkeepalived.go
pkg/monitor/monitor.go

When generating keepalived.conf we are relying on the logic to gather IPs of all the cluster nodes for the IP stack used by the specific VIP. This logic currently relies only on the addresses reported as part of Node.Status.Addresses.
In some scenarios it may be that the node is not reporting all its IPs via kubelet but still have those available. If we detect such a scenario (e.g. kubelet reporting only IPv4, but VIP being IPv6), we will check for Node annotations created by OVN as those use different source of truth so kubelet not reporting IPs is not affecting it.
The newly introduced behaviour is just a fallback in case Node.Status.Addresses does not contain an IP of a requested stack, therefore not changing the behaviour for currently working scenarios.
Contributes-to: …

OPNET-197: Extend logic for detecting Node IP

---

pkg/config/node.go

There is no err return in IsTheSameConfig()

node.go: remove no required check

---

pkg/config/node.go

- node.go: remove no required check
- Only return false from isUpgradeStillRunning when ALL node groups have same config, not just one of them

OCPBUGS-11138: fix isUpgradeStillRunning()

---

pkg/utils/addresses.go
pkg/utils/addresses_test.go
pkg/utils/network.go
pkg/utils/network_test.go
pkg/utils/utils.go

This PR hardens the logic of selecting node IP by adding more sophisticated way of detecting IPv6 addresses. This is because there is a class of IPv4-mapped-to-IPv6 addresses which are represented in the same way as vanilla IPv4 addresses when using net.IP structures.
In order to make our logic smarter, we now analyse subnet mask to decide if an address is IPv6 or IPv4. This is because we may have an address `::ffff:192.168.0.160/64` which contains both `:` and `.` making the regular logic unreliable. Knowing that the biggest mask for IPv4 is /32 we may detect if such an address is an IPv4-mapped-to-IPv6 address or vanilla IPv4.
To solve the case of IPv4-mapped-to-IPv6 address in a huge v6 subnet (e.g. `::ffff:192.168.0.160/16`) we are also checking for the capacity of the struct storing …

OCPBUGS-10695: Use subnet mask to detect IP stack

---

pkg/config/node.go

- node.go: remove no required check
- Only return false from isUpgradeStillRunning when ALL node groups have same config, not just one of them

OCPBUGS-11297: fix isUpgradeStillRunning()

---

pkg/monitor/dynkeepalived.go

Currently the nested configs that were used to enable dual stack VIPs do not respect the EnableUnicast setting correctly, which in the case of EUS upgrades that skip 4.11 can cause problems with the unicast migration being triggered at an incorrect time.
This patch just propagates the EnableUnicast setting into the nested configs so it will apply correctly in dual stack VIP environments.

OCPBUGS-12729: Make nested dual stack VIP configs respect EnableUnicast

---

pkg/monitor/dynkeepalived.go

This PR modifies the logging so that when printing complex structs we don't print pointer addresses but the underlying content. This will help debugging issues when keepalived configuration is generated incorrectly.

OCPBUGS-12739: In keepalived config print structs instead of pointers

---

test/data/keepalived.conf.tmpl

With this change whenever keepalived adds an IP address to the interface, the IP will be explicitly labeled as "vip". This is in order for anyone relying on the output of `ip a` to be able to distinguish between the IP addresses configured by the network and IP addresses coming from keepalived.
Until now looking only at the output of `ip a` wasn't a reliable way of distinguishing host IP from VIP. There were heuristics possible like e.g. treating IP with /32 as VIP but those are not always as reliable as we would like (e.g. for IPv6 the mask /128 is used also by real host IP).
Contributes-to: OCPBUGS-4370

OCPBUGS-4370: Add label to VIP via keepalived

---

pkg/config/node.go

This PR modifies the logging so that when we fail to parse the OVN annotation on the Node CR, we also print the error message. Currently the error message is quietly dropped so we can see that we failed, but we don't see why.
Contributes-to: OCPBUGS-12739

OCPBUGS-12739: Print error message when node annotation doesn't parse

---

pkg/config/node.go

With this PR we are going to print a dump of the whole Node object in case when an attempt to get the Node IPs fails. This should help debug cases when we are trying to parse an empty annotation even when we believe it contains the required data.
Contributes-to: OCPBUGS-12739

OCPBUGS-12739: Dump whole Node object when failing to get node IP

---

pkg/config/node.go

With this PR the logic of getting the Node IP from OVN annotations is becoming lazy, i.e. it stops running as soon as the first matching IP is found. This is to remediate a scenario in which the node has multiple matching IP addresses and some parts of the code use the first one, whereas other parts of the code use the last one matching.
E.g. we have a code that collects
```
IngressVIP:fd65:a1a8:60ad:271c::201
```
and for the same node we have the OVN annotation containing
```
'["192.168.90.29","fd65:a1a8:60ad:271c::71","fd65:a1a8:60ad:271c:9e72:83b8:ffa6:ece1"]'
```
With the current logic, we will have
```
time="2023-05-30T09:19:41Z" level=info msg="For node ci-ln-wmb6p1b-c1627-gdhjq-master-0 can't find address using NodeInternalIP. Fallback to OVN annotation." …
```

OCPBUGS-12739: Use lazy match when getting IP from OVN

---

pkg/config/node.go

This PR extends the logic of using OVN annotations for selecting keepalived peers. With this change we will at first try to use local Node IP if available and only afterwards run the full heuristic that uses OVN annotations.
By using `GetVRRPConfig()` for generating both NonVirtualIP and entry in `IngressConfig.Peers` list we should guarantee that `participateInIngressVRPP` evaluates correctly even if node has multiple IP addresses in the same subnet.
Contributes-to: OCPBUGS-12739

OCPBUGS-12739: Use NonVirtualIP as a hint for selecting Peers

---

pkg/config/net.go
pkg/config/node.go

Fixing a bug where instead of `net.ParseIP()` we called `net.IP()`. This was causing a malformed IP address to be passed around which ultimately was causing us to always think we are in IPv4 setup.
Contributes-to: OCPBUGS-12739

OCPBUGS-12739: Fix bug with IP conversion using net.IP

---

pkg/config/node.go
pkg/monitor/dynkeepalived.go

It turns out that the mapping of roles to machine-configs is more complex than we realized when we first implemented the unicast migration and it's causing bugs in more complex environments with nodes in multiple roles. The machineconfiguration.openshift.io/state annotation directly provides us the upgrade status of the node anyway, so there's no reason to try to derive it ourselves. I'm unsure why we didn't use that in the first place, but I don't see any reason not to.
Note that it was also proposed to just use the kubelet version check we previously added to handle EUS upgrades. However, in my testing that doesn't always align perfectly with the node's state so I'm concerned that nodes may schedule the migration incorrectly if we rely only on that. Using both kubelet version and state …

OCPBUGS-14403: Use machine-config state instead of comparing roles

---

pkg/config/node.go
pkg/monitor/dynkeepalived.go

This is a manual cherry-pick of #261 . It did not backport cleanly due to changes in how the client for GetNodes is created. Otherwise, all changes applied cleanly.

[release-4.12] OCPBUGS-15315: Use machine-config state instead of comparing roles

---

pkg/config/net.go
pkg/config/node.go

This PR cherry-picks the following commits
* 681a56a5b60f03d9adf9b53b13b6ce0a7c72e1de (#252)
* a9da48e4209e8f55b39fefa3d5af934c08eafc1e (#253)
* 8e0b38426819518fe04171d454d6dc791eb7289b (#254)
* 49ecffdb7e785c3af5696110e2c994fd581caa58 (#256)
* 0212952ca31e4bd64aaeeee4b517b3226627ac46 (#258)
that have all been created as part of OCPBUGS-12739

OCPBUGS-14487: Support IPv6 VIP for setup with multipe IPv6 addresses

---

pkg/config/node.go
pkg/monitor/dynkeepalived.go

This is a manual cherry-pick of #262 . It appears the backport was not clean simply due to whitespace changes.

[release-4.11] OCPBUGS-15539: Use machine-config state instead of comparing roles

---

pkg/monitor/dynkeepalived.go

When we stopped rendering config if we were unable to update the peer list[0] we also stopped checking the haproxy firewall rule status if there was a problem contacting the API. What this means is that we may not correctly update the priority of a node with no access to the API, causing the VIP to stay there when it should migrate to a different node.
I think this will mostly happen during initial deployment when the apiserver may become briefly unavailable. If this happens haproxy will remove the firewall rule so we fall back to direct un-loadbalanced API access, but if there isn't an apiserver instance running on the node yet that won't work either. There's no way for the healthchecks to recover from this situation.
To fix this I just moved the firewall rule check to be first in the …

OCPBUGS-18257: Move haproxy firewall rule check earlier in loop

---

pkg/monitor/dynkeepalived.go

When we stopped rendering config if we were unable to update the peer list[0] we also stopped checking the haproxy firewall rule status if there was a problem contacting the API. What this means is that we may not correctly update the priority of a node with no access to the API, causing the VIP to stay there when it should migrate to a different node.
I think this will mostly happen during initial deployment when the apiserver may become briefly unavailable. If this happens haproxy will remove the firewall rule so we fall back to direct un-loadbalanced API access, but if there isn't an apiserver instance running on the node yet that won't work either. There's no way for the healthchecks to recover from this situation.
To fix this I just moved the firewall rule check to be first in the …

[release-4.11] OCPBUGS-18815: Move haproxy firewall rule check earlier in loop

---

pkg/monitor/dynkeepalived.go

We are increasing timeout for waiting for boostrap keepalived from the current 30 seconds to 30 minutes. This is because we observed environments where 30 seconds is not enough for the kube-api to start yet it does start eventually after much longer time.
We don't understand why kube-api is so slow on the bootstrap node in those cases but as this timeout has no any deeper meaning it is safe to just increase it to extremely big value.
Contributes-to: OCPBUGS-19492

OCPBUGS-19492: Increase timeout for bootstrap kubeapi

---

pkg/monitor/dynkeepalived.go

This is a manual cherry-pick of https://github.com/openshift/baremetal-runtimecfg/pull/276

[release-4.12] OCPBUGS-20127: Increase timeout for bootstrap kubeapi

---

test/data/keepalived.conf.tmpl

This PR modifies the label used for an IP address assigned by keepalived to not include the name of the interface. This is because the maximum allowed lenght of the label is 15 characters, causing stuff to fail when interface itself has a name longer than 12 characters.
With this change the label will always be a simple string of length 3 and will not be susceptible to overflow for long NIC names.
Contributes-to: OCPBUGS-23432

OCPBUGS-23432: Use shorter IP label for keepalived VIP

---

cmd/corednsmonitor/corednsmonitor.go
cmd/runtimecfg/display.go
cmd/runtimecfg/render.go
pkg/config/node.go
pkg/config/node_test.go
pkg/monitor/corednsmonitor.go
pkg/monitor/dnsmasqmonitor.go
pkg/monitor/dynkeepalived.go

Add the ability to render and monitor Cloud LB IPs. This capability is used only when `userProvisionedDNS` is enabled on some (AWS, GCP and Azure) cloud platforms via install-config.
On some cloud platforms (AWS, Azure, GCP), the user cannot use the cloud's default DNS solution. They are expected to use their own custom DNS solution that is external to the cluster. OpenShift is not allowed to configure this DNS solution. In this scenario, these same customers want to continue using the cloud provided Load Balancers (LBs).
OpenShift is expected to continue configuing the cloud LBs for API, API-Int and Ingress access. Since the LB information is not available, before cluster installation, the user cannot configure their custom DNS solution before cluster installation.
So, to support this …

CORS-2818: Adding ability to render Cloud LB IPs

---

.snyk

These files either come from other projects or are not used in production so there's no reason to security scan them.

OCPBUGS-26765: Add .snyk file to ignore vendor and test files

---

pkg/utils/addresses.go
pkg/utils/addresses_test.go

This PR extends the logic of validating IP addresses whether suitable to be used as Node IP by adding a case when an IP address is marked as Egress IP (by e.g. OpenShift SDN). Those should never be used as Node IPs, thus we ignore them.

OCPBUGS-29095: Ignore egress IP when selecting Node IP

---

cmd/runtimecfg/node-ip.go

In https://github.com/openshift/baremetal-runtimecfg/pull/301 we have decreased level from INFO to DEBUG for multiple messages around Node IP detection logic. However, we never implemented ability to enable DEBUG level so that those logs were effectively unreachable.
With this PR we will consume `ENABLE_NODEIP_DEBUG` env variable and if configured, we will increase log level.
For OpenShift customers the variable will be consumed via ConfigMap as defined in the respective Pod manifest in the MCO repository.
Fixes: OCPBUGS-32348

OCPBUGS-32348: Make log level configurable

---

Dockerfile

go.mod for quite some time defines golang version as 1.21, yet Dockerfile was never upgraded from 1.18
In order to make local builds possible again, we need to bump golang version in Dockerfile.

NO-ISSUE: Fix wrong golang version, bump to 1.21

---

pkg/config/node.go
pkg/config/node_test.go

This PR adds logic for extracting IP addresses for the Node from a newly added OVN annotation `k8s.ovn.org/host-cidrs`.
Till now we were only using the `k8s.ovn.org/host-addresses` annotation which is now deprecated in favour of the one mentioned above.
Fixes: OCPBUGS-34706

OCPBUGS-34706: Add support for OVN HostCidrs annotation

---

pkg/config/node.go

In https://github.com/openshift/baremetal-runtimecfg/pull/313 we have fixed some logic regarding to VIPs in ELB scenario, but we forgot to handle the error. Because of this, even if we detected the IP correctly, the function could stil return a non-empty error causing the installation to fail.
This PR contains a simple fix to return `nil` instead of `err` in case we managed to recover from the issue.
A second commit fixes the issue where the change was missing additional part of the code that had the same flaw, i.e. generation of ingress config.
Fixes: OCPBUGS-32141

OCPBUGS-32141: Fix handling of ELB Node IP detection

---

Dockerfile

CentOS Stream 8 has gone out of support and because of that the mirrorlist record no longer exists. This causes local builds to fail and doesn't match what we're actually using in the product now anyway. This just moves the image from stream8 to stream9.

OPNET-552: Move to stream9 for local builds

---

pkg/monitor/iptables.go

Previously we ignored errors from the exists call in the firewall rule check. This can cause problems if the check fails for reasons other than the non-existence of the rule, such as a permission error on iptables. If the check returns err we should handle that and report the problem rather than just report that the firewall rule doesn't exist (which may or may not be true).

OCPBUGS-38281: Handle errors in iptables healthcheck

---

pkg/monitor/monitor.go

Once the HAProxy firewall rule has been created we do not expect it to need to be removed in normal functioning of the cluster. The more important part of this check is to ensure that we don't insert the rule before HAProxy is fully configured and ready to accept API traffic. Removing the rule due to health check failures is more of an escape hatch in case of an unexpected failure of HAProxy.
This increases the required failure count to 11. That should ensure we never fail the check in less than 60 seconds, which is important now that the HAProxy health checks may take up to 15 seconds to detect a failure in a backend. The previous value of 3 meant we might trigger a failure in as little as 12 seconds, which is shorter than the 15 second worst case to detect a backend outage.

OCPBUGS-44694: Extend haproxy-monitor fall time

---

pkg/monitor/monitor.go

Once the HAProxy firewall rule has been created we do not expect it to need to be removed in normal functioning of the cluster. The more important part of this check is to ensure that we don't insert the rule before HAProxy is fully configured and ready to accept API traffic. Removing the rule due to health check failures is more of an escape hatch in case of an unexpected failure of HAProxy.
This increases the required failure count to 11. That should ensure we never fail the check in less than 60 seconds, which is important now that the HAProxy health checks may take up to 15 seconds to detect a failure in a backend. The previous value of 3 meant we might trigger a failure in as little as 12 seconds, which is shorter than the 15 second worst case to detect a backend outage.
(cherry …

[release-4.17] OCPBUGS-48766: Extend haproxy-monitor fall time

---

go.mod
go.sum
vendor/github.com/sirupsen/logrus/README.md
vendor/github.com/sirupsen/logrus/hooks/test/test.go
vendor/github.com/sirupsen/logrus/writer.go
vendor/modules.txt

The old one is failing the security check. 1.9.3 should be new enough to pass.

OCPBUGS-48194: Bump logrus version

---

Dockerfile
pkg/utils/utils.go

This is the runtimecfg change corresponding to
https://github.com/openshift/machine-config-operator/pull/4767
which switches the monitor call to the HAProxy endpoing rather than
call through to the API.
I also included a commit to bump the Dockerfile image to golang 1.22 to match the current state of the code.

OPNET-629: Use HAProxy monitor endpoint instead of API

---

Dockerfile
pkg/utils/utils.go

Reverts openshift/baremetal-runtimecfg#336

Revert "OPNET-629: Use HAProxy monitor endpoint instead of API"

---

cmd/corednsmonitor/corednsmonitor.go

Include cloud platform specific parameters to argument list for corednsmonitor

OCPBUGS-48469: Include cloud platform specific parameters to argument list for corednsmonitor 

---

pkg/config/node.go
pkg/monitor/dynkeepalived.go

Following the [enhancement](https://github.com/openshift/enhancements/blob/master/enhancements/arbiter-clusters.md) for TNA clusters, we want to install this new type of cluster using Assisted-Service.
Currently there is a problem when installing TNA clusters using Assisted-Service, because in Assisted-Service one of the master nodes acts as the bootstrap. So during the installation there will only be one master node, but we need two in order for keepalived-monitor to configure keepalived.
We cannot wait until the bootstrap finishes and becomes a master, because then no node will have the API vip.
To circumvent that we will add the arbiter node to the list of nodes.

OCPEDGE-1689: Include Arbiter nodes in the API backends if there is only one master

---

cmd/runtimecfg/node-ip.go

This was added and reverted back when we first started to support configurable logging. It was eventually replaced by the config-map, but there are circumstances where we want to always enable debug logging, specifically in the nodeip-configuration service. Using the env var will let us set it in the service and always have it take effect, regardless of the user settings.

OCPBUGS-55971: Re-add ENABLE_NODEIP_DEBUG env var
