README.md, cmd/runtimecfg.go, test/data/keepalived.conf.tmpl
This command allows you to pass .tmpl Go templates to render
=> Add render command

pkg/config/node.go, pkg/utils/utils.go
This is so the etcd-# short hostname can be used.
=> Add EtcdShortHostname to Node

pkg/config/node.go, test/data/Corefile.tmpl
=> runtimecfg: Add DNS upstream servers for Corefile

test/data/config.hcl.tmpl
=> runtimecfg: Add EtcdShortHostname to test data

Dockerfile, pkg/monitor/iptables.go, scripts/ip6tables
Extend moniotr logic to support IPv6
=> Monitor - add IPv6 support

Makefile
This adds a Makefile target for CI to run unit tests
=> Add test target for CI

OWNERS
Now that everybody has made a few commits, let's have all be able to
approve.
=> OWNERS: Add the rest of the team

pkg/config/node.go, pkg/monitor/monitor.go, test/data/haproxy.cfg.tmpl
Add support for IPv6 frontend in Haproxy
=> Haproxy add support for IPv6 frontend

cmd/runtimecfg/runtimecfg.go, pkg/config/node.go
With this tool, an operator will be able to easily determine before
deployment if the cluster names chosen will end up with conflicting
Virtual Router IDs. One can't use the same Virtual Router ID for
different VIPs in the same multicast domain.
Usage example:
$ ./runtimecfg vr-ids cnf10
APIVirtualRouterID: 147
DNSVirtualRouterID: 158
IngressVirtualRouterID: 2
$ ./runtimecfg vr-ids cnf11
APIVirtualRouterID: 228
DNSVirtualRouterID: 239
IngressVirtualRouterID: 147
In this example, we can see that cluster cnf10 would end up with the
API virtual router id conflicting with cnf11's ingress router id. In
this case, if both clusters share the same control plane multicast
domain, different cluster names should be chosen.
=> bug 1821667: runtimecfg: tool to show the Virtual Router IDs

cmd/corednsmonitor/corednsmonitor.go, cmd/dynkeepalived/dynkeepalived.go, cmd/runtimecfg/display.go, cmd/runtimecfg/render.go, pkg/config/node.go, pkg/monitor/corednsmonitor.go, pkg/monitor/dnsmasqmonitor.go, pkg/monitor/dynkeepalived.go
=> Delete DNS-VIP and DNSVirtualRouterID          

pkg/utils/addresses.go, pkg/utils/addresses_test.go
The existing implementation of node-ip lookup using default routes
may return different results if an address moves from a physical
interface to a bridge. If there are multiple default routes, this
may change the order in which we retrieve the addresses. Because we
only take the first one, this will cause us to select a different
address, which can break the node configuration.
To fix this, we need to sort the addresses based on the priority of
the associated default route. This will have no effect when there is
a single default route, but it will ensure we always return the
default route addresses in the same order no matter what order the
interfaces are in.
=> Sort node-ip addresses based on default route priority

pkg/config/node.go, pkg/monitor/corednsmonitor.go
Now that node resolution is not needed for bootstrapping, we can
retrieve the list of nodes from the api in the coredns monitor
instead of having to maintain a coredns plugin. This adds a new
field to the cluster config that is populated with a list of the
nodes in the cluster, their addresses, and whether the address is
ipv6. This can be used in the coredns Corefile template to provide
node addresses statically.
=> Add node resolution to corednsmonitor

pkg/monitor/dynkeepalived.go
Ironic has started using the API VIP for access, and as a result we
need to keep the VIP available when Ironic is. The apiserver can go
down periodically during bootstrapping, so that isn't a reliable way
to keep the VIP alive on its own.
This change adds another check when the apiserver check fails. It
will ping Ironic and if Ironic is still up then it won't count the
check as failed and will keep the VIP active.
Note that previously Ironic was never stopped on the boostrap node.
Doing that will be a pre-requisite to this functionality as we do
need to allow keepalived to stop once bootstrapping is complete so
the VIP moves to the masters. Since bootstrapping can't complete
until after Ironic has provisioned the masters, if we stop Ironic
after provisioning then this check won't prevent …
=> Bug 1949859: Add Ironic healthcheck to bootstrap keepalived checks

pkg/config/node.go
In case of dual-stack deployment, both IPV4 and IPV6 addresses assigned to a node,
CoreDNS should resolve hostname for both addresses.
=> Bug 1995468: CoreDNS Corefile hosts - add support for dual-stack

OWNERS
Toni and Yossi have moved to different teams so they aren't reviewing
in this repo anymore. We also have Christoph and Douglas working on
this now so we should have them on the list.
=> Update OWNERS to reflect current team

cmd/runtimecfg/node-ip.go
In #181 we fixed a problem where ipv6 addresses are initially in a
state that is not usable by services. However, this was only done
for the code path where VIPs are in use, so it only applies to IPI
deployments that are not using remote workers. It turns out this is
also happening on non-IPI deployments (and likely for IPI deployments
with remote workers), so we need to run the same check on that code
path.
=> OCPBUGS-669: Apply ipv6 bind check to non-VIP case too

pkg/utils/addresses.go, pkg/utils/addresses_test.go
How to test:
~~~
launch openshift/baremetal-runtimecfg#199 metal,ipv6
~~~
=> OCPBUGS-2512: Improve IP address sort order for interface selection

OWNERS
Remove myself (@creydr) as an approver/reviewer as I switched the the team
=> Remove creydr as a reviewer and approver

cmd/runtimecfg/node-ip.go
[OPNET-133](https://issues.redhat.com//browse/OPNET-133): Support remote worker in onprem installations
1. Create file that will be used by keepalived in case chosen ip is
different from vips (remote worker)
2. Set remote worker label that will be used by ingress
=> OPNET-133: Support remote worker in onprem installations

cmd/runtimecfg/node-ip.go
Introducing a new option (false by default): `--user-managed-lb`
If this option is set, we'll not mark a worker node as a remote-worker
if a chosen IP doesn't match the VIPs.
Since the VIPs are managed externally, we don't need to care about it.
=> OPNET-214: node-ip: adjust logic for user-managed-lb

pkg/monitor/dynkeepalived.go
If there is an error retrieving either the ingress or api peer list, we should not continue with config rendering. If there are three identical failures in a row it will cause us to render a config with no unicast peers, which can cause a split-brain with other nodes that are still using unicast.
This adds a return of the error from updateUnicastConfig and handles it in the calling code. In the case of the migration code, we loop until the list is retrieved successfully since we can't proceed without peers. In the case of a normal config update we just skip that iteration and retry on the next time interval.
=> OCPBUGS-15947: Don't render config with incomplete unicast peer list

cmd/runtimecfg/node-ip.go
This reverts commit 0561ac232cd8c56913173fd14fb855376bcbbaf8.
=> Revert "OCPBUGS-32348: Make log level configurable"

pkg/monitor/dynkeepalived.go
The control loop that manages /var/run/keepalived/iptables-rule-exists looks at the error returned by os.Stat and decides that the file exists as long as os.IsNotExist returns false. In other words, if the error is some non-nil error other than NotExist, the sentinel file would not be created.
Added more logging here and changed the logic so that there will always be an attempt to create the file if it does not exist and the rules are present.
=> OCPBUGS-38288: Distinguish NotExist from nil for keepalived sentinel file errors.

OWNERS
As part of my onboarding and as discussed with @mkowalski I am adding myself as a reviewer.
=> NO-ISSUE: Add emy as reviewer
